sudo: required

language: go

go:
  - "1.15"

env:
  global:
    - IMAGE_NAME=storageos/init
    - IMAGE_TAG=test
    - K8S_VERSION="v1.18.6"

before_install:
  - |
      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md)|(\.MD)|(\.png)|(\.pdf)|^(doc/)|^(MAINTAINERS)|^(LICENSE)'; then
        # Do not skip if it's a tagged build.
        if [[ -z "$TRAVIS_TAG" ]]; then
          echo "Only doc files were updated, not running the CI."
          exit
        fi
      fi
  - sudo apt -y update && sudo apt install -y jq
  - go get github.com/golang/mock/gomock
  - go get github.com/golang/mock/mockgen

jobs:
  include:
    - script: ./e2e.sh
    - stage: deploy
      script:
        - make image
      before_deploy:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        - provider: script
          script: bash deploy.sh tagged
          on:
            tags: true
        - provider: script
          script: bash deploy.sh develop
          on:
            branch: master
