[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.1"

[prune]
  go-tests = true
  unused-packages = true
