name: Publish release image

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set image tag env var
        # Refer https://stackoverflow.com/a/58178121 for git tag extraction.
        run: echo "IMAGE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set image env vars
        run: |
          echo "IMAGE=storageos/init:${{ env.OPERATOR_IMAGE_TAG }}" >> $GITHUB_ENV
      - name: Login to docker container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
      - name: Build container image
        run: make docker-build
      - name: Push container image to dockerhub
        run: make docker-push
