name: Publish release image

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    name: Publish container image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set image env
        # Refer https://stackoverflow.com/a/58178121 for git tag extraction.
        run: echo ::set-env name=IMAGE::storageos/init:${GITHUB_REF#refs/*/}
      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}
      - name: Build container image
        run: make docker-build
      - name: Push container image
        run: make docker-push